### ISSUE TITLE
Library does not set the "Host" header when writing data to ThingSpeak

### ISSUE THREAD

**Issue by v-c** [elecfreaks/pxt-esp8266iot#5]
See the definition here: https://github.com/elecfreaks/pxt-esp8266iot/blob/2ac4ed8b500eb9a233413c009f80bdd7bede96d1/ESP8266.ts#L236

It does not set the "Host" header, which is required. HTTP/1.1 request without Host header is invalid (by RFC2616)

**Comment by v-c** [comment]
CC: @elecfreaks1 @lionyhw  @waltfe

**Comment by v-c** [comment]
On further investigation it appears that the issue is that the "Host" header is not being set causing ThingSpeak to reject the request.

**Comment by elecfreaks1** [comment]
I have not been able to reproduce the problem you mentioned. I tried write data to ThingSpeak with this function and is worked. Please update to the latest module and try again.

**Comment by v-c** [comment]
@elecfreaks1 Not sure what you mean by "latest module". The latest real code updates to this repo seem to be quite old.

**Comment by elecfreaks1** [comment]
@v-c 
We successfully used the #2.1.12 release version to write data to the ThingSpeak platform, and it worked.

Please confirm that the repository version you are using is the same. If you still encounter issues with data upload, providing screenshots of the blocks could help us better understand and resolve the problem.
